config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :dosts
  #get 'home/index'
  get 'home/about'
  # root 'home#index'
  root 'dosts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dost.rb
class Dost < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        has_many :dosts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dosts_controller.rb
class DostsController < ApplicationController
  before_action :set_dost, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show ]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /dosts or /dosts.json
  def index
    @dosts = Dost.all
  end

  # GET /dosts/1 or /dosts/1.json
  def show
  end

  # GET /dosts/new
  def new
    @dost = current_user.dosts.build
  end

  # GET /dosts/1/edit
  def edit
  end

  # POST /dosts or /dosts.json
  def create
    #  dost = Dost.new(dost_params)
    @dost = current_user.dosts.build(dost_params)

    respond_to do |format|
      if @dost.save
        format.html { redirect_to @dost, notice: "Dost was successfully created." }
        format.json { render :show, status: :created, location: @dost }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dosts/1 or /dosts/1.json
  def update
    respond_to do |format|
      if @dost.update(dost_params)
        format.html { redirect_to @dost, notice: "Dost was successfully updated." }
        format.json { render :show, status: :ok, location: @dost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dosts/1 or /dosts/1.json
  def destroy
    @dost.destroy
    respond_to do |format|
      format.html { redirect_to dosts_url, notice: "Dost was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
   @dost = current_user.dosts.find_by(id: params[:id])
   redirect_to dosts_path, notice: "Not authorized to edit this dost" if @dost.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dost
      @dost = Dost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dost_params
      params.require(:dost).permit(:first_name, :ladt_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_me = "My name is Ahsan"
    @answer = 2 + 2
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dosts_helper.rb
module DostsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/dosts/_form.html.erb
<div class="card">
  <div class="card-header">
    <%= form_with(model: dost) do |form| %>
        <% if dost.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(dost.errors.count, "error") %> prohibited this dost from being saved:</h2>
            <ul>
              <% dost.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>    
  </div>
  <div class="card-body">
    <div class="field form-group">
      <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
    </div>
    <br/>
    <div class="field">

      <%= form.text_field :ladt_name, class:"form-control", placeholder:"Last Name" %>
    </div>
    <br/>
    <div class="field">
      <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
    </div>
    <br/>
    <div class="field">
      <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
    </div>
    <br/>
    <div class="field">
      <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
    </div>
    <br/>
    <div class="field">
      <%= form.number_field :user_id, id: :dosts_user_id, class:"form-control", value: current_user.id, type: :hidden %>
    </div>
  </div>
</div>
<br/>
<div class="actions">
  <%= form.submit class:"btn btn-secondary"%>
  <br/>
<% end %>

app/views/dosts/edit.html.erb
<h1>Editing Dost</h1>

<%= render 'form', dost: @dost %>
<br/>
<%= link_to 'Show', @dost, class:"btn btn-dark" %> 
<%= link_to 'Delete', @dost, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
<%= link_to 'Back', dosts_path, class:"btn btn-dark" %>

app/views/dosts/index.html.erb
<% if user_signed_in? %>
  <table class="table table-striped table-hover table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
        <th> Remove user</th>
      </tr>
    </thead>

    <tbody>
      <% @dosts.each do |dost| %>
        <% if dost.user == current_user %>
        <tr>
          <td><%= link_to dost.first_name + ' ' + dost.ladt_name, dost %></td> 
          <td><%= dost.email %></td>
          <td><%= dost.phone %></td>
          <td><%= dost.twitter %></td>
          <td><%= link_to 'Delete', dost, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Dost', new_dost_path, class:"btn btn-secondary" %>
<% else %>
  <h1>Hello world</h1>
  <p>This is my first ruby page</p>
<% end %>

app/views/dosts/new.html.erb
<h1>Add new Dost</h1>
<br/>
<%= render 'form', dost: @dost %>
<br/>
<%= link_to 'Back', dosts_path, class:"btn btn-dark" %>

app/views/dosts/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @dost.first_name %>
    <%= @dost.ladt_name %>
  </h1>
  <p class="lead">
    <%= @dost.email %>  |
    <%= @dost.phone %>  |
    <%= @dost.twitter %>
  </p>

<%= link_to 'Edit', edit_dost_path(@dost), class:'btn btn-secondary' %> 
<%= link_to 'Delete', @dost, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
<%= link_to 'Back', dosts_path, class:'btn btn-secondary' %>

</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friend App',
        root_path, class: 'navbar-brand' %>
    <%# <a class="navbar-brand" href="#">Friend App</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About us',
              home_about_path, class: 'nav-link'%>
        </li>
        
        <% if user_signed_in? %>
          
          <li class="nav-item">
          <%= link_to 'Add Dost',
              new_dost_path, class: 'nav-link'%>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign out',
                destroy_user_session_path, method: :delete, class: 'nav-link'%>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit profile',
                edit_user_registration_path, class: 'nav-link'%>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign up',
                new_user_registration_path, class: 'nav-link'%>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign in',
                user_session_path, class: 'nav-link'%>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>This is my about us page</h1>

<p>
<%= @about_me %>
</p>

<p>
Sum : 
<%= @answer %>
</p>

app/views/home/index.html.erb
<h1>Hello World!</h1>
<p>Found in app/views/home/index.html.erb</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-primary d-flex align-items-center" role="alert">
  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </svg>
  <div>
    <%= notice %>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Friends App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class='container'>
    <br/>
    <% if notice%>
      <%= render 'layouts/alerts' %>
    <% end %>
    
    <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>